# Exported from Render on 2026-01-27T08:12:25Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: serverindex1
      runtime: node
      repo: https://github.com/trulol1/Server-Dashboard
      plan: free
      envVars:
      - key: APP_NAME
        sync: false
      - key: TOTP_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      region: virginia
      buildCommand: npm install
      startCommand: node server.js
      autoDeployTrigger: commit
